# syntax=docker/dockerfile:1.7

# ===== Build stage =====
FROM node:22-alpine AS build
WORKDIR /app
RUN corepack enable

# Cache deps first (lockfile-driven)
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
RUN pnpm install --frozen-lockfile

# Copy sources and build.
# NOTE: VITE_API_BASE_URL is no longer the primary config path — it's only the
# build-time fallback used when neither window.__APP_CONFIG__ nor /config.js is
# present (i.e., local dev). Runtime API URL is injected via /config.js, which
# is generated by docker/30-configjs.sh from $API_BASE_URL env at container
# start. Same image works for dev/prod without rebuild.
COPY . .
RUN pnpm build

# ===== Runtime stage (pure static nginx; no reverse proxy) =====
FROM nginx:1.27-alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html
# Generate /config.js from $API_BASE_URL at container start.
COPY docker/30-configjs.sh /docker-entrypoint.d/30-configjs.sh
RUN chmod +x /docker-entrypoint.d/30-configjs.sh
EXPOSE 80
